#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping Auxcast listeners...\n"
sudo update-rc.d listen-for-shutdown.sh remove
sudo /etc/init.d/listen-for-shutdown.sh stop
sudo update-rc.d listen-for-cast.sh remove
sudo /etc/init.d/listen-for-cast.sh stop

echo "=> Removing Auxcast...\n"
sudo rm -rf /usr/local/bin/listen-for-shutdown.py 
sudo rm -rf /etc/init.d/listen-for-shutdown.sh 
sudo rm -rf /usr/local/bin/listen-for-cast.py 
sudo rm -rf /etc/init.d/listen-for-cast.sh 

echo "Auxcast uninstalled.\n"
